@ECHO OFF

:: UPDATE WITH LOCAL PATH(s)
SET CRYPTOLENS_ROOT=C:\DevProjects\cryptolens-cpp\root

:: CRYPTO CONFIG
SET LICENSE_RSA_PUB_KEY_MOD="uALu9ugIgbCAsJkVyfxZozdcuZMMDdyu4hFJfsj6C8DYPFrsH3+VX5ACGB3GMjGpNE43ZJr2OD8OCct4S+A0ZvbNR7FT67A2iyY1Q+xUmDTL1LWnidPVueSZsXCqv3Oj2kUofWubhfd/cAlw5ryG44uGd++enTQlqU4jP3ZoBXXEPnxvTPCPGzZ5E/t2JMFa8pZKTYrHfrq9C3cOsZ9S3vzXHVi6mAYfhr6TWyJ47rDcaAxhepeKfGJdTrKVtYLC90rsDnz0OqnxGTlQQsyL5//h+VecpqQQShvkmctGFjnuJvKq94O6n1nEWtcK0mR4JDwGihdIJ3MUlqjyi27w8w=="
SET LICENSE_RSA_PUB_KEY_EXP="AQAB"
::* Get Key; * Activate; * Deactivate;	
SET LICENSE_AUTH_TOKEN="WyIxMDE0MDc1MiIsInJIa2lvYm5YSTVJWGJGSzZDTTlscUVyNXdhNDhRTHNDK1ptNXloN3oiXQ=="
SET LICENSE_PRODUCT_ID=13666
SET LICENSE_TIMEOUT_SECONDS=120
SET ENABLE_LICENSE_CHECK=1

:: BUILD
MKDIR build
CD build
cmake .. -DREPO_BUILD_WRAPPER:BOOL=ON -DLICENSE_CHECK:BOOL=ON -DLICENSE_RSA_PUB_KEY_MOD:STRING=%LICENSE_RSA_PUB_KEY_MOD% -DLICENSE_RSA_PUB_KEY_EXP:STRING=%LICENSE_RSA_PUB_KEY_EXP% -DLICENSE_AUTH_TOKEN:STRING=%LICENSE_AUTH_TOKEN% -DLICENSE_PRODUCT_ID:STRING=%LICENSE_PRODUCT_ID% -DLICENSE_TIMEOUT_SECONDS:STRING=%LICENSE_TIMEOUT_SECONDS% -Tv140
cmake --build . --config Release
CD ..


